### ISSUE TITLE
[Feature Request] Add a dummy sound device to the image

### ISSUE THREAD

**Issue by hillbicks** [GioF71/squeezelite-docker#172]
**Is your feature request related to a problem? Please describe.**
The challenge I have is the following: I'm trying to enhance the usability of our multiroom audio setup. I'm using LMS together with home assistant for this. My goal is to have one dummy device where music/news are started and then sync the other players to it, if they're supposed to play. This way I won't have to worry about syncing groups and which device was actually the first in the group.

**Describe the solution you'd like**
I haven't tested this yet, but from these sources the additional entries for the docker should look like this. 

```
FROM debian:stretch-slim
USER root
RUN apt-get update && apt-get install -y kmod
RUN touch /etc/modprobe.d/myalias.conf
RUN echo "alias char-major-116 snd" >> /etc/modprobe.d/myalias.conf
RUN echo "alias snd-card-0 snd-dummy" >> /etc/modprobe.d/myalias.conf
RUN modprobe snd-dummy
```
and run the container as privileged. 

**Describe alternatives you've considered**
Alternative would be to fallback on the sync logic with existing and real devices. Either I'm too stupid to figure out how to do this right, or it really isn't that straight forward. 

**Additional context**

https://superuser.com/questions/1451294/how-to-get-alsa-dummy-soundcard-on-debian-in-docker
https://old.reddit.com/r/linux4noobs/comments/2m77g1/help_a_noob_create_a_dummy_sound_card_driver/

If this is something that you would consider adding to the container, I would see if I can confirm these settings to be working and then posting them here. 

Let me know what you think and thank you for providing this image.

**Comment by GioF71** [comment]
Hello, I will try it, I cannot guarantee an ETA though.

**Comment by GioF71** [comment]
Hello, just to keep track of the progress and of the things to do in order to accomplish this in a clean way...

- alsa-base should be installed
- /lib/modules should be mounted

**Comment by GioF71** [comment]
I should also verify if loading snd-dummy must be executed on the host machine as well

**Comment by GioF71** [comment]
Hello, just a concern here.
It seems that when I try the procedure, the "Dummy" device is visible to the host system also (just checked with `cat /proc/asound/cards`).
So, doing this in the container actually affects the host system.
If this is the case, can you just create the dummy output on the host device and use the container as usual?
Even when the container is stopped and removed, the additional audio cards stays there.

What do you think?

**Comment by hillbicks** [comment]
That is strange, but also makes sense. 

I actually thought about just creating the dummy device on the host and then adding that device to the container. But then you'd loose the portability of the container, you'd have to create the device on the new host. But if that happens anyway, then I guess it is better to keep it simple. 

I'll try and get the squeezelite image up with a dummy sound card from the host and report back here with progress and a bit of documentation.

**Comment by GioF71** [comment]
Hello @hillbicks, did you find some sort of solution?
I forgot to mention, the fact that changes in the container are not limited to the container scope, would require a logic to be applied in order to avoid that the container creates multiple dummy cards (once for each restart).

I also wanted to suggest a different solution, using mpd and upmpdcli. I have both docker containers for those.
MPD supports a "Null" output which does not require the creation of a dummy card. Upmpdcli creates a Upnp/Dlna renderer on top of mpd, and logitech media server allows to play to a upnp renderer via the plugin named "UPnP/DLNA bridge". This might be a little convoluted, but not too much, and would not require any change to the underlying alsa configuration.

Let me know what you think about this workaround, and in case, if you need help configuring the containers.

Cheers

**Comment by GioF71** [comment]
Hello @hillbicks, can we close the issue?
Thank you

**Comment by GioF71** [comment]
Closing, feel free to reopen or create a new one if there are relevant news.
Thank you
